service: myserverlessproject

frameworkVersion: "3"

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: serverless-bucket-upload-regi
      localDir: uploadData

provider:
  name: aws
  runtime: nodejs18.x
  profile: regi

# you can overwrite defaults here
#  stage: dev
  region: eu-central-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  hello:
    handler: handler.hello

# you can add CloudFormation resource templates here
resources:
 Resources:
   DemoBucketUpload:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: serverless-bucket-upload-regi

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
