service: myserverlessproject

frameworkVersion: "3"

plugins:
  - serverless-s3-sync
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  profile: regi
  httpApi:
    cors: true
#  stage: dev
  region: eu-central-1
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
        - s3:*
        - ses:*
      Resource: '*'

package:
  individually: true

custom:
  tableName: player-points
  bucketName: serverless-bucket-upload-regi
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: uploadData

functions:
  getPlayerScore:
    handler: lambdas/endpoints/getPlayerScore.handler
    events:
      - httpApi:
          method: GET
          path: /get-player-score/{ID}
  createPlayerScore:
    handler: lambdas/endpoints/createPlayerScore.handler
    events:
      - httpApi:
          method: POST
          path: /create-player-score/{ID}
  createFile:
    handler: lambdas/endpoints/createFile.handler
    events:
      - httpApi:
          method: POST
          path: /create-file/{fileName}
  getFile:
    handler: lambdas/endpoints/getFile.handler
    events:
      - httpApi:
          method: GET
          path: /get-file/{fileName}
  sendEmail:
    handler: lambdas/endpoints/sendEmail.handler
    events:
      - httpApi:
          method: POST
          path: /send-email

# add CloudFormation resource templates here
resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode:  PAY_PER_REQUEST
         


