service: myserverlessproject

frameworkVersion: "3"

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  tableName: player-points
  s3Sync:
    - bucketName: serverless-bucket-upload-regi
      localDir: uploadData

provider:
  name: aws
  runtime: nodejs18.x
  profile: regi
  httpApi:
    cors: true

#  stage: dev
  region: eu-central-1

functions:
  getUser:
    handler: lambdas/getUser.handler
    events:
      - httpApi:
          method: GET
          path: /getuser/{ID}

# add CloudFormation resource templates here
resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-bucket-upload-regi
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode:  PAY_PER_REQUEST
         


